---
title: "Untitled"
author: "Jeffrey Arnold"
date: "6/6/2018"
output: html_document
---

```{r}
library("tidyverse")
library("tools")
```


```{r}
## this function is essentially the same as R Core's from the URL
## http://developer.r-project.org/CRAN/Scripts/depends.R
getDB <- function() {
    contrib.url(getOption("repos")["CRAN"], "source") # trigger chooseCRANmirror() if required
    description <- sprintf("%s/web/packages/packages.rds", getOption("repos")["CRAN"])
    con <- if(substring(description, 1L, 7L) == "file://") {
        file(description, "rb")
    } else {
        url(description, "rb")
    }
    on.exit(close(con))
    db <- readRDS(gzcon(con))
    rownames(db) <- db[,"Package"]

    db
}

```

```{r}
db <- getDB() %>%
  # there are some duplicate column names
  as_tibble(validate = FALSE)  
```

See https://rviews.rstudio.com/2018/03/08/cran-package-metadata/


```{r}
clean <- function(x){
  str_replace(x, "\\[[^]]*]", "") %>%
    str_replace("[\r\n]", "")
}

```

```{r}
db %>% 
  mutate(Author = clean(Author)) %>%
  select(Author, Maintainer, `Authors@R`) %>%
  mutate(map(`Authors@R`, eval))
```


